# Generated by Django 3.0.5 on 2020-06-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_id', models.CharField(max_length=30)),
                ('team_mem2', models.CharField(max_length=100)),
                ('team_mem3', models.CharField(max_length=100)),
                ('team_mem1', models.CharField(max_length=100)),
            ],
        ),
    ]
