# Generated by Django 3.0.5 on 2020-06-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITSP', '0003_auto_20200622_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_id',
            new_name='teamid',
        ),
    ]
